config/routes.rb
Rails.application.routes.draw do
  resources :elegidas

  resources :usuarios

  resources :respuestas

  resources :preguntas

  get 'inicios/index'

  get 'inicios/enviado_ok'
  post 'inicios/enviado_ok'

   root 'inicios#index'

end

app/models/elegida.rb
class Elegida < ActiveRecord::Base
end

app/controllers/elegidas_controller.rb
class ElegidasController < ApplicationController
  before_action :set_elegida, only: [:show, :edit, :update, :destroy]

  # GET /elegidas
  # GET /elegidas.json
  def index
    @elegidas = Elegida.all
  end

  # GET /elegidas/1
  # GET /elegidas/1.json
  def show
  end

  # GET /elegidas/new
  def new
    @elegida = Elegida.new
  end

  # GET /elegidas/1/edit
  def edit
  end

  # POST /elegidas
  # POST /elegidas.json
  def create
    @elegida = Elegida.new(elegida_params)

    respond_to do |format|
      if @elegida.save
        format.html { redirect_to @elegida, notice: 'Elegida was successfully created.' }
        format.json { render :show, status: :created, location: @elegida }
      else
        format.html { render :new }
        format.json { render json: @elegida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elegidas/1
  # PATCH/PUT /elegidas/1.json
  def update
    respond_to do |format|
      if @elegida.update(elegida_params)
        format.html { redirect_to @elegida, notice: 'Elegida was successfully updated.' }
        format.json { render :show, status: :ok, location: @elegida }
      else
        format.html { render :edit }
        format.json { render json: @elegida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elegidas/1
  # DELETE /elegidas/1.json
  def destroy
    @elegida.destroy
    respond_to do |format|
      format.html { redirect_to elegidas_url, notice: 'Elegida was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elegida
      @elegida = Elegida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def elegida_params
      params.require(:elegida).permit(:pregunta_id, :respuesta_id, :usuario_id)
    end
end

app/helpers/elegidas_helper.rb
module ElegidasHelper
end

app/views/elegidas/_form.html.erb
<%= form_for(@elegida) do |f| %>
  <% if @elegida.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@elegida.errors.count, "error") %> prohibited this elegida from being saved:</h2>

      <ul>
      <% @elegida.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pregunta_id %><br>
    <%= f.number_field :pregunta_id %>
  </div>
  <div class="field">
    <%= f.label :respuesta_id %><br>
    <%= f.number_field :respuesta_id %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.number_field :usuario_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/elegidas/edit.html.erb
<h1>Editing elegida</h1>

<%= render 'form' %>

<%= link_to 'Show', @elegida %> |
<%= link_to 'Back', elegidas_path %>

app/views/elegidas/index.html.erb
<h1>Listing elegidas</h1>

<table>
  <thead>
    <tr>
      <th>Pregunta</th>
      <th>Respuesta</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elegidas.each do |elegida| %>
      <tr>
        <td><%= elegida.pregunta_id %></td>
        <td><%= elegida.respuesta_id %></td>
        <td><%= elegida.usuario_id %></td>
        <td><%= link_to 'Show', elegida %></td>
        <td><%= link_to 'Edit', edit_elegida_path(elegida) %></td>
        <td><%= link_to 'Destroy', elegida, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Elegida', new_elegida_path %>

app/views/elegidas/new.html.erb
<h1>New elegida</h1>

<%= render 'form' %>

<%= link_to 'Back', elegidas_path %>

app/views/elegidas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pregunta:</strong>
  <%= @elegida.pregunta_id %>
</p>

<p>
  <strong>Respuesta:</strong>
  <%= @elegida.respuesta_id %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @elegida.usuario_id %>
</p>

<%= link_to 'Edit', edit_elegida_path(@elegida) %> |
<%= link_to 'Back', elegidas_path %>