config/routes.rb
Rails.application.routes.draw do
  resources :elegidas

  resources :usuarios

  resources :respuestas

  resources :preguntas

  get 'inicios/index'

  get 'inicios/enviado_ok'
  post 'inicios/enviado_ok'

   root 'inicios#index'

end

app/models/pregunta.rb
class Pregunta < ActiveRecord::Base
	has_many :respuestas, dependent: :destroy
	accepts_nested_attributes_for :respuestas, reject_if: proc { |attributes| attributes['nombre'].blank? }, allow_destroy: true
end

app/controllers/preguntas_controller.rb
class PreguntasController < ApplicationController
  before_action :set_pregunta, only: [:show, :edit, :update, :destroy]

  # GET /preguntas
  # GET /preguntas.json
  def index
    @preguntas = Pregunta.all
  end

  # GET /preguntas/1
  # GET /preguntas/1.json
  def show
  end

  # GET /preguntas/new
  def new
    @pregunta = Pregunta.new
    @pregunta.respuestas.build
  end

  # GET /preguntas/1/edit
  def edit
    @pregunta.respuestas.build
  end

  # POST /preguntas
  # POST /preguntas.json
  def create
    @pregunta = Pregunta.new(pregunta_params)

    respond_to do |format|
      if @pregunta.save
        format.html { redirect_to @pregunta, notice: 'Pregunta was successfully created.' }
        format.json { render :show, status: :created, location: @pregunta }
      else
        format.html { render :new }
        format.json { render json: @pregunta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preguntas/1
  # PATCH/PUT /preguntas/1.json
  def update
    respond_to do |format|
      if @pregunta.update(pregunta_params)
        format.html { redirect_to @pregunta, notice: 'Pregunta was successfully updated.' }
        format.json { render :show, status: :ok, location: @pregunta }
      else
        format.html { render :edit }
        format.json { render json: @pregunta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preguntas/1
  # DELETE /preguntas/1.json
  def destroy
    @pregunta.destroy
    respond_to do |format|
      format.html { redirect_to preguntas_url, notice: 'Pregunta was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pregunta
      @pregunta = Pregunta.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pregunta_params
      params.require(:pregunta).permit!
    end
end

app/helpers/preguntas_helper.rb
module PreguntasHelper
end

app/views/preguntas/_form.html.erb
<%= form_for(@pregunta, :html => { class: 'form-horizontal'}) do |f| %>
  <% if @pregunta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pregunta.errors.count, "error") %> prohibited this pregunta from being saved:</h2>

      <ul>
      <% @pregunta.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre, class: 'col-sm-1 control-label' %>
    <div class="col-sm-5">
      <%= f.text_field :nombre, class: 'form-control' %>
    </div>    
  </div>


  <h2>Respuestas</h2>  
  <%= f.fields_for :respuestas do |respuesta| %>
    <div class="form-group">
      <%= respuesta.label :nombre, class: 'col-sm-1 control-label' %>
      <div class="col-sm-5">
        <%= respuesta.text_field :nombre, class: 'form-control' %>
      </div>      
    </div>
  <% end %>
  
  
    <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>
<br>

app/views/preguntas/edit.html.erb
<h1>Editing pregunta</h1>

<%= render 'form' %>

<%= link_to 'Ver', @pregunta, class: 'btn btn-default' %>
<%= link_to 'Regresar', preguntas_path, class: 'btn btn-default' %>

app/views/preguntas/index.html.erb
<div class="page-header">
  <h1>Lista de Preguntas</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>id</th>
      <th>Nombre</th>
      <th>ResP. 1</th>
      <th>Resp. 2</th>
      <th>Resp. 3</th>
      <th>Resp. 4</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @preguntas.each do |pregunta| %>
      <tr>
        <td><%= pregunta.id %></td>
        <td><%= pregunta.nombre %></td>
        <% if pregunta.respuestas.any? %>
          <% cantidad_respuestas = pregunta.respuestas.count %>
          <% if cantidad_respuestas == 4 %>
            <td><%= pregunta.respuestas[0][:nombre] %></td>
            <td><%= pregunta.respuestas[1][:nombre] %></td>
            <td><%= pregunta.respuestas[2][:nombre] %></td>
            <td><%= pregunta.respuestas[3][:nombre] %></td>
          <%  elsif cantidad_respuestas == 3 %>
            <td><%= pregunta.respuestas[0][:nombre] %></td>
            <td><%= pregunta.respuestas[1][:nombre] %></td>
            <td><%= pregunta.respuestas[2][:nombre] %></td>
            <td></td>
          <%  elsif cantidad_respuestas == 2 %>
            <td><%= pregunta.respuestas[0][:nombre] %></td>
            <td><%= pregunta.respuestas[1][:nombre] %></td>
            <td></td>
            <td></td>
          <%  elsif cantidad_respuestas == 1 %>
            <td><%= pregunta.respuestas[0][:nombre] %></td>
            <td></td>
            <td></td>
            <td></td>
          <% else %>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          <% end %>
        <% else %>
        <% end %>        
        <td>
          <%= link_to 'Ver', pregunta, class: 'btn btn-default btn-sm' %>
          <%= link_to 'Editar', edit_pregunta_path(pregunta), class: 'btn btn-default btn-sm' %>
          <%= link_to 'Eliminar', pregunta, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Pregunta', new_pregunta_path, class: 'btn btn-primary' %>

app/views/preguntas/new.html.erb
<h1>New pregunta</h1>

<%= render 'form' %>

<%= link_to 'Back', preguntas_path %>

app/views/preguntas/show.html.erb
<p id="notice"><%= notice %></p>

<h1><strong>Pregunta:</strong>  <%= @pregunta.nombre %></h1>
<hr>


  <% if @pregunta.respuestas.any? %>
    <ul>
      <% @pregunta.respuestas.each do |respuesta| %>
        <li><%= respuesta.nombre %></li>
      <% end %>
    </ul>
  <% else %>
    <p>None available</p>
  <% end %>

<hr>
<%= link_to 'Editar', edit_pregunta_path(@pregunta), class: 'btn btn-default' %>
<%= link_to 'Regresar', preguntas_path, class: 'btn btn-default' %>