config/routes.rb
Rails.application.routes.draw do
  resources :elegidas

  resources :usuarios

  resources :respuestas

  resources :preguntas

  get 'inicios/index'

  get 'inicios/enviado_ok'
  post 'inicios/enviado_ok'

   root 'inicios#index'

end

app/models/respuesta.rb
class Respuesta < ActiveRecord::Base
	belongs_to :pregunta	
end

app/controllers/respuestas_controller.rb
class RespuestasController < ApplicationController
  before_action :set_respuesta, only: [:show, :edit, :update, :destroy]

  # GET /respuestas
  # GET /respuestas.json
  def index
    @respuestas = Respuesta.all
  end

  # GET /respuestas/1
  # GET /respuestas/1.json
  def show
  end

  # GET /respuestas/new
  def new
    @respuesta = Respuesta.new
  end

  # GET /respuestas/1/edit
  def edit
  end

  # POST /respuestas
  # POST /respuestas.json
  def create
    @respuesta = Respuesta.new(respuesta_params)

    respond_to do |format|
      if @respuesta.save
        format.html { redirect_to @respuesta, notice: 'Respuesta was successfully created.' }
        format.json { render :show, status: :created, location: @respuesta }
      else
        format.html { render :new }
        format.json { render json: @respuesta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /respuestas/1
  # PATCH/PUT /respuestas/1.json
  def update
    respond_to do |format|
      if @respuesta.update(respuesta_params)
        format.html { redirect_to @respuesta, notice: 'Respuesta was successfully updated.' }
        format.json { render :show, status: :ok, location: @respuesta }
      else
        format.html { render :edit }
        format.json { render json: @respuesta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /respuestas/1
  # DELETE /respuestas/1.json
  def destroy
    @respuesta.destroy
    respond_to do |format|
      format.html { redirect_to respuestas_url, notice: 'Respuesta was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_respuesta
      @respuesta = Respuesta.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def respuesta_params
      params.require(:respuesta).permit(:nombre, :pregunta_id)
    end
end

app/helpers/respuestas_helper.rb
module RespuestasHelper
end

app/views/respuestas/_form.html.erb
<%= form_for(@respuesta) do |f| %>
  <% if @respuesta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@respuesta.errors.count, "error") %> prohibited this respuesta from being saved:</h2>

      <ul>
      <% @respuesta.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :pregunta_id %><br>
    <%= f.number_field :pregunta_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/respuestas/edit.html.erb
<h1>Editing respuesta</h1>

<%= render 'form' %>

<%= link_to 'Show', @respuesta %> |
<%= link_to 'Back', respuestas_path %>

app/views/respuestas/index.html.erb
<h1>Listing respuestas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Pregunta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @respuestas.each do |respuesta| %>
      <tr>
        <td><%= respuesta.nombre %></td>
        <td><%= respuesta.pregunta_id %></td>
        <td><%= link_to 'Show', respuesta %></td>
        <td><%= link_to 'Edit', edit_respuesta_path(respuesta) %></td>
        <td><%= link_to 'Destroy', respuesta, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Respuesta', new_respuesta_path %>

app/views/respuestas/new.html.erb
<h1>New respuesta</h1>

<%= render 'form' %>

<%= link_to 'Back', respuestas_path %>

app/views/respuestas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @respuesta.nombre %>
</p>

<p>
  <strong>Pregunta:</strong>
  <%= @respuesta.pregunta_id %>
</p>


  

<%= link_to 'Edit', edit_respuesta_path(@respuesta) %> |
<%= link_to 'Back', respuestas_path %>